- .github/workflows/node.js.yml
- packages/client/src/GamePage.tsx
This is so that the tests get run whenever there is a push or PR to main.  In the future we might want to run a linter in this workflow too.
> Create a GitHub workflow (CI)

- README.md
- packages/server/package.json
- packages/server/src/db.ts
- packages/server/src/games.ts
- packages/server/src/index.ts
- packages/shared/src/api_types.ts
- yarn.lock
Fixes #6 
Games will now persist through server resets.
The database is MongoDB.  One functional change is that the IDs are now MongoDB unique identifiers rather than an auto-incrementing number.
> Add a database

- packages/vue-client/src/components/TaegeukStone.vue
- packages/vue-client/src/components/boards/MulticolorGridBoard.vue
- packages/vue-client/src/router/index.ts
- packages/vue-client/src/views/ComponentView.vue
This is a milestone for Simultaneous Fractional Go.  I haven't plugged this in to a Variant yet, but it has been tried out a bit on a new route `/components`
> Multicolor Grid Board

- packages/server/src/api.ts
- packages/server/src/index.ts
- packages/vue-client/src/requests.ts
- packages/vue-client/vite.config.ts
To ensure URL consistency between production and development and to avoid conflicting URLs between client and server projects.
> Locate server ressources at /api for production

- .vscode/extensions.json
@JonKo314 @merowin We had some discussion in the chat about recommended extensions - I believe this config file tells VSCode to recommend these extensions to people opening this workspace.
> Extension recommmnedations

- packages/shared/src/abstractAlternatingOnGrid/abstractAlternatingOnGrid.ts
- packages/shared/src/baduk/baduk.ts
- packages/shared/src/coordinate.test.ts
- packages/shared/src/coordinate.ts
- packages/shared/src/grid.ts
- packages/shared/src/index.ts
- packages/shared/src/parallel/parallel.ts
- packages/vue-client/src/components/boards/BadukBoard.vue
- packages/vue-client/src/components/boards/MulticolorGridBoard.vue
- packages/vue-client/src/components/boards/ParallelGoBoard.vue
There was a lot of duplicate `decodeMove` `encodeMove` `coordsToLetters` (mostly my fault haha).  This PR moves this logic into a class called `Coordinate`.  One alternative of course is to keep these as functions that operate on `CoordinateLike` objects, but to me these functions seem very tied to the {x, y} data structure, hence the object oriented approach - let me know what you think.
> Coordinate

- packages/server/.eslintrc.cjs
- packages/server/package.json
- packages/server/src/api.ts
- packages/server/src/games.ts
- packages/server/src/index.ts
- yarn.lock
#65 got wonky, here's take two.
> Eslint for packages/server (take two)

- packages/shared/src/abstractAlternatingOnGrid/abstractAlternatingOnGrid.ts
- packages/shared/src/abstract_game.ts
- packages/shared/src/baduk/baduk.ts
- packages/shared/src/badukWithAbstractBoard/badukWithAbstractBoard.ts
- packages/shared/src/game_map.ts
- packages/shared/src/parallel/parallel.ts
- packages/vue-client/src/components/GameCreationForm.vue
Fixes #25
Related issue: #8 
This makes it so that the initial config is actually valid for the selected variant.
> Add default configs

- packages/shared/src/coordinate.ts
- packages/shared/src/grid.ts
- packages/shared/src/parallel/parallel.test.ts
- packages/shared/src/parallel/parallel.ts
> [parallel] Add captures.

- packages/vue-client/src/components/boards/BadukBoardAbstract.vue
> Make viewBox of polygonal board fit intersections

- packages/shared/.eslintrc.cjs
- packages/shared/package.json
- packages/shared/src/abstractAlternatingOnGrid/abstractAlternatingOnGrid.ts
- packages/shared/src/abstract_game.ts
- packages/shared/src/badukWithAbstractBoard/abstractBoard/BadukBoardAbstract.ts
- packages/shared/src/badukWithAbstractBoard/abstractBoard/PolygonalBoardHelper.ts
- packages/shared/src/badukWithAbstractBoard/abstractBoard/intersection.ts
- packages/shared/src/badukWithAbstractBoard/badukWithAbstractBoard.ts
- packages/shared/src/parallel/parallel.ts
- yarn.lock
Fixes #36 (this was the final step)
> Add eslint to the shared package and fix errors.

- packages/server/.eslintrc.cjs
- packages/server/package.json
- packages/server/src/games.ts
- packages/server/src/index.ts
This might help with #38, but still a lot of things to do for that task
For those not familiar:
```
async function someAsyncFunct() {
throw new Error("lol oops");
}
// somewhere else, this will crash the server!!
someAsyncFunc();
```
Now you have to catch these things, which is safer:
```
someAsyncFunc().catch((e) => console.log(`Error: ${e}`));
```
> Eslint server no-floating-promises

- packages/server/src/api.ts
> More coherent error messages for illegal moves.

- packages/vue-client/src/views/GameView.vue
> Show game result after the game ends.

- packages/shared/src/baduk/baduk.ts
- packages/shared/src/capture/capture.test.ts
- packages/shared/src/capture/capture.ts
- packages/shared/src/capture/index.ts
- packages/shared/src/game_map.ts
- packages/shared/src/index.ts
- packages/vue-client/src/board_map.ts
Requested in the forums: https://forums.online-go.com/t/playing-atari-go-online/45759
> Capture go

- packages/vue-client/src/views/GameView.vue
If the user sits at exactly one seat in a game,
select that seat when the game is loaded
closes #85
> Select seat on reload

- packages/server/package.json
- packages/server/src/index.ts
- yarn.lock
Added a MongoDB session store to persist Express sessions. This should resolve https://github.com/benjaminpjones/govariants/issues/80
> Persist user sessions to database

- packages/shared/src/baduk/baduk.test.ts
- packages/shared/src/baduk/baduk.ts
- packages/shared/src/ko_detector.test.ts
- packages/shared/src/ko_detector.ts
This is a situational superko, but could be made configurable in the future.
This also adds a SuperKoDetector class with a basic test.  The object is not hard to use - just push state every time the game state changes.
> Detect Ko in Baduk

- packages/shared/src/abstract_game.ts
- packages/shared/src/baduk/baduk.ts
- packages/shared/src/badukWithAbstractBoard/badukWithAbstractBoard.ts
- packages/shared/src/parallel/parallel.ts
I think the symmetry appealed to me, but there just hasn't been a good use for it.
> Remove AbstractGame.prototype.importState

- packages/server/package.json
- packages/server/src/api.ts
- packages/server/src/index.ts
- packages/server/src/users.ts
- packages/shared/src/api_types.ts
- packages/vue-client/src/components/UserNav.vue
- packages/vue-client/src/router/index.ts
- packages/vue-client/src/stores/user.ts
- packages/vue-client/src/views/LoginView.vue
- packages/vue-client/src/views/RegisterView.vue
- yarn.lock
Fixes #5
https://github.com/govariantsteam/govariants/assets/25233703/e7cf563e-55b5-42e8-876d-f01b7a992721
> Allow registration and login with username and password

- packages/vue-client/src/views/GameView.vue
This clears up the console on the GameView page.
> Don't throw an error if the variant not yet known.

- packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/BadukBoardAbstract.ts
- packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/CircularBoardHelper.ts
- packages/shared/src/variants/badukWithAbstractBoard/badukWithAbstractBoard.ts
- packages/vue-client/src/components/GameCreation/BadukWithAbstractBoardConfigForm.vue
- packages/vue-client/src/components/boards/BadukBoardAbstract.vue
> Circular Go

- packages/shared/src/variants/__tests__/baduk.test.ts
- packages/shared/src/variants/baduk.ts
> Fix the scoring bug and add another test.

- packages/shared/src/lib/grid.ts
- packages/shared/src/variants/__tests__/baduk.test.ts
- packages/shared/src/variants/baduk.ts
Fixes #128
Fixing a bug while deleting tens of lines of code! Never a bad thing!
> Replace custom flood fill functions with group_utils functions.

- packages/shared/src/game_map.ts
- packages/shared/src/variants/__tests__/baduk.test.ts
- packages/shared/src/variants/__tests__/thue_morse.test.ts
- packages/shared/src/variants/baduk.ts
- packages/shared/src/variants/thue_morse.ts
- packages/vue-client/src/board_map.ts
- packages/vue-client/src/config_form_map.ts
Fixes #16
https://github.com/govariantsteam/govariants/assets/25233703/0192adec-fdba-46fe-8232-103620a6812f
> Thue-Morse

- packages/shared/src/index.ts
- packages/shared/src/variants/freeze.ts
- packages/vue-client/src/board_map.ts
- packages/vue-client/src/components/boards/FreezeGoBoard.vue
- packages/vue-client/src/components/boards/MulticolorGridBoard.vue
Just a little flair :)
https://github.com/govariantsteam/govariants/assets/25233703/0e9807eb-b629-48fe-81cf-ee95bed1dee6
> FreezeGo: board turns blue if the board is frozen

- packages/shared/src/game_map.ts
- packages/shared/src/variants/__tests__/one_color.test.ts
- packages/shared/src/variants/one_color.ts
- packages/vue-client/src/board_map.ts
- packages/vue-client/src/config_form_map.ts
> Add One Color Go

- packages/vue-client/src/components/boards/ParallelGoBoard.vue
> Parallel Board: Don't stage passes at 'pa'

- packages/server/src/games.ts
- packages/server/src/time-control.ts
- packages/shared/src/time_control/index.ts
- packages/shared/src/time_control/time_control.utils.ts
- packages/vue-client/src/components/GameCreation/GameCreationForm.vue
- packages/vue-client/src/views/GameView.vue
this should fix https://github.com/govariantsteam/govariants/issues/155
> bugfix time control config form

- package.json
- packages/vue-client/src/components/GameCreation/GameCreationForm.vue
- packages/vue-client/src/components/GameList.vue
- packages/vue-client/src/components/GameTimer.vue
- packages/vue-client/src/components/boards/BadukBoard.vue
- packages/vue-client/src/components/boards/BadukBoardAbstract.vue
- packages/vue-client/src/components/boards/FractionalBoard.vue
- packages/vue-client/src/components/boards/KeimaBoard.vue
- packages/vue-client/src/components/boards/MulticolorGridBoard.vue
- packages/vue-client/src/components/boards/ParallelGoBoard.vue
- packages/vue-client/src/views/GameView.vue
added a prettier config, then run yarn lint in the root directory.
I'm hoping that this will replace all newline stuff (CRLF -> LF), and maybe there will be less changes on lint in future. But I don't know much about this, so ...
> add prettier config, lint project

- packages/server/src/index.ts
> set cookie max age to 180 days

- packages/vue-client/src/App.vue
- packages/vue-client/src/assets/base.css
- packages/vue-client/src/assets/main.css
- packages/vue-client/src/components/GameListItem.vue
- packages/vue-client/src/components/UserNav.vue
Here is an attempt to anchor the nav bar (to the top) an rework its style. We made some layout changes at high-level of the dom structure, so I'm looking forward to your review.
- Anchor the nav bar to top and make it sticky
- Replace "Home" with the Logo
- Style the nav entries consistently
My partner and I worked on this together :-)
> 99 anchor the nav bar

- packages/server/src/api.ts
- packages/server/src/games.ts
- packages/shared/src/api_types.ts
- packages/shared/src/lib/utils.ts
- packages/vue-client/src/assets/main.css
- packages/vue-client/src/components/GameCreation/GameCreationForm.vue
- packages/vue-client/src/components/GameCreation/TimeControlConfigForm.vue
- packages/vue-client/src/components/GameList.vue
- packages/vue-client/src/components/GamesFilterForm.vue
Issue: https://github.com/govariantsteam/govariants/issues/172
Prototype for a way to filter for games of one variant, and / or games where the user has taken a seat.
> Games filter (prototype)

- packages/server/src/index.ts
> change local origin to explicit ip

- packages/server/src/api.ts
- packages/server/src/games.ts
- packages/vue-client/src/views/GameView.vue
fixes #195
pretty much just copied the code from playMove
Not sure if error code 500 is correct in this case, but this prevents the server from crashing.
> 195 server crashes on game request with wrong

- packages/server/src/api.ts
- packages/vue-client/src/views/GameView.vue
fixes #201 
catch the error "Seat taken"
notify clients on seat update
> notify clients on seat change

- packages/vue-client/.postcssrc.json
- packages/vue-client/package.json
- yarn.lock
> Add PostCSS Nesting plugin

- packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/BadukBoardAbstract.ts
- packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/SierpinskyBoard.ts
- packages/shared/src/variants/badukWithAbstractBoard/badukWithAbstractBoard.ts
- packages/vue-client/src/components/GameCreation/BadukWithAbstractBoardConfigForm.vue
- packages/vue-client/src/components/GameCreation/GameCreationForm.vue
Adds board pattern for sierpinsky triangle:
> add sierpinsky triangle board

- packages/shared/src/game_map.ts
- packages/shared/src/index.ts
- packages/shared/src/variants/__tests__/quantum.test.ts
- packages/shared/src/variants/baduk.ts
- packages/shared/src/variants/quantum.ts
- packages/vue-client/src/board_map.ts
- packages/vue-client/src/components/boards/QuantumBoard.vue
- packages/vue-client/src/config_form_map.ts
UPDATE (3/24): Implementation should be complete!  Feel free to leave feedback :)
https://github.com/govariantsteam/govariants/assets/25233703/784be9f5-8e29-4b8d-b871-20de82412f62
---
As of Feb 19, it's not functional at all, but this is the boilerplate that needs to be in place to get a variant added.  It just shows two boards with a quantum stone hard-coded at the 3-4 point:
> Quantum Go

- packages/shared/src/variants/quantum.ts
Oops, forgot this doesn't default to "Resign" "Pass"
> Allow pass in Quantum Go.

- packages/shared/src/variants/quantum.ts
sorry, bad merge.  Here's a fix-forward
> Add bracket

- packages/vue-client/src/components/boards/KeimaBoard.vue
> Fix keima previews

- packages/server/src/time-control/time-handler-parallel.ts
- packages/server/src/time-control/time-handler-sequential.ts
- packages/server/src/time-control/time-handler-utils.ts
#223 is going to have a lot of extra code if we don't clean up first.  The two handlers share a lot of code, this diff moves some of that code into shared functions.
> Dedup handlers

- packages/shared/src/variants/__tests__/parallel.test.ts
@merowin already pointed out in the issue (#231) that the problem is not with the variant, but this codifies that assertion.
> timeout unit tests for the parallel variant

- packages/server/package.json
- packages/vue-client/package.json
- packages/vue-client/src/components/GameList.vue
- packages/vue-client/src/components/GameListItemFallback.vue
- yarn.lock
Fixes #157 
Wraps game list items in an ErrorBoundary.
Had to rebase on top of #236 to use these games with config errors, but this should work for other types of errors too.
> Place ErrorBoundary around list items in Game list.

- packages/server/Procfile
This is the follow-up to #242 
I have removed the Multi Procfile buildpack and environment variable, and the server is still up.  Now just time to clean up the unused one.
Resolves #37
> Remove server/Procfile

- packages/shared/src/lib/graph.ts
- packages/shared/src/lib/grid.ts
- packages/shared/src/lib/group_utils.ts
- packages/shared/src/variants/__tests__/quantum.test.ts
- packages/shared/src/variants/baduk.ts
- packages/shared/src/variants/drift.ts
- packages/shared/src/variants/keima.ts
- packages/shared/src/variants/one_color.ts
- packages/shared/src/variants/phantom.ts
- packages/shared/src/variants/pyramid.ts
- packages/shared/src/variants/quantum.ts
- packages/vue-client/src/components/boards/BadukBoard.vue
@merowin, this fixes the build errors by introducing a `GridBaduk` adapter class.  This class has the same interface as the original `Baduk` class.
> Revert to 2D array board and introduce GridBaduk class

- README.md
For easy access to information about the variant demo page.
> Add info about variant demos to README.md

- packages/server/src/api.ts
- packages/server/src/games.ts
- packages/server/src/index.ts
- packages/shared/src/api_types.ts
- packages/shared/src/variants/fractional/fractional.test.ts
- packages/shared/src/variants/fractional/fractional.ts
- packages/vue-client/src/components/boards/FractionalBoard.vue
- packages/vue-client/src/views/GameView.vue
Reverts govariantsteam/govariants#267
Reverting this because this merge crashed the site, my bad.
> Revert "send state via api instead of all moves"

- packages/server/src/api.ts
- packages/server/src/games.ts
- packages/server/src/index.ts
- packages/shared/src/api_types.ts
- packages/shared/src/variants/fractional/fractional.test.ts
- packages/shared/src/variants/fractional/fractional.ts
- packages/vue-client/src/components/GameCreation/BadukConfigForm.vue
- packages/vue-client/src/components/boards/FractionalBoard.vue
- packages/vue-client/src/views/GameView.vue
Reverts govariantsteam/govariants#271
> Revert "Revert "send state via api instead of all moves""

- packages/vue-client/src/components/boards/QuantumBoard.vue
fixes: https://github.com/govariantsteam/govariants/issues/281
I believe I unfortunately broke this with the pr: #277
> fix layout for quantum with graph board

- packages/server/src/api.ts
- packages/shared/src/variants/__tests__/quantum.test.ts
- packages/shared/src/variants/quantum.ts
- yarn.lock
Code is much more simple and allows the user to download the file at any point in the game.
> simpler implementation of sgf download

- packages/shared/src/variants/__tests__/quantum.test.ts
- packages/shared/src/variants/quantum.ts
- packages/vue-client/src/components/boards/QuantumBoard.vue
A couple bugs:
- I introduced a bug in #284  where specialMoves threw an error during the quantum phase
- #270: toSgfRepr throwing error on non-grid boards with coordinates greater than 52
> Quantum bug fixes

- packages/shared/src/lib/__tests__/sgf_recorder.test.ts
- packages/shared/src/lib/sgf_recorder.ts
- packages/shared/src/variants/baduk.ts
This diff introduces a class dedicated to SGF, and adds it to the Baduk variant.  This also gives Baduk subclasses SGF capabilities.
I am happy to report that SGF seems to tolerate changes in player order, so variants like Keima are able to be parsed by other programs like OGS.
> Sgf for Baduk and its subclasses

- packages/server/src/api.ts
> block game creation unless user is logged in

- packages/shared/src/variant.ts
- packages/shared/src/variant_map.ts
- packages/shared/src/variants/baduk.ts
- packages/shared/src/variants/badukWithAbstractBoard/badukWithAbstractBoard.ts
- packages/shared/src/variants/capture.ts
- packages/shared/src/variants/drift.ts
- packages/shared/src/variants/fractional/fractional.ts
- packages/shared/src/variants/freeze.ts
- packages/shared/src/variants/keima.ts
- packages/shared/src/variants/phantom.ts
- packages/shared/src/variants/pyramid.ts
- packages/shared/src/variants/quantum.ts
- packages/shared/src/variants/tetris.ts
- packages/shared/src/variants/thue_morse.ts
- packages/vue-client/src/components/GameView/PlayerSymbol.vue
- packages/vue-client/src/components/GameView/SeatComponent.vue
- packages/vue-client/src/views/GameView.vue
- packages/vue-client/src/views/VariantDemoView.vue
> add player symbol component

- packages/shared/src/lib/ko_detector.ts
- packages/shared/src/variants/baduk.ts
- packages/shared/src/variants/thue_morse.ts
> Remove Ko-detection in Thue-Morse

- packages/server/src/api.ts
- packages/server/src/users.ts
- packages/shared/src/api_types.ts
I created functionality to update user ratings as well as a simple function that is available if a username needs to be changed.
For now, the rating type is a number, but later it will be the type indicated by Glicko2. I wanted to add the Glicko2 library to the project in another commit for clarity.
> functionality to update rating and username in database

- packages/vue-client/src/components/PlayingTable/ThueMorseTable.vue
https://github.com/govariantsteam/govariants/pull/327#discussion_r1842805153
> Address comment NewGridBadukConfig -> DefaultBoardConfig

- packages/server/src/time-control/time-handler-map.ts
This adds Quantum and SFractional to the time handler map.
> add quantum and sfractional to time handler map

- packages/vue-client/src/views/VariantDemoView.vue
> preselect seat in demo

- packages/shared/src/templates/quantum_rules.ts
- packages/shared/src/templates/tetris_rules.ts
- packages/vue-client/src/assets/main.css
This adds a line in the quantum rules description for completeness, also I tried to improve the Tetris rules description.
> complete quantum rules, improve tetris rules

- packages/shared/src/index.ts
- packages/shared/src/variant_map.ts
- packages/shared/src/variants/lighthouse/lighthouse.ts
- packages/shared/src/variants/lighthouse/lighthouse.types.ts
- packages/vue-client/src/board_map.ts
- packages/vue-client/src/components/boards/LighthouseBoard.vue
- packages/vue-client/src/components/boards/MulticolorGridBoard.vue
- packages/vue-client/src/config_form_map.ts
Reverts govariantsteam/govariants#363
> Revert "Revert "Lighthouse (renamed)""

- packages/server/.eslintrc.cjs
- packages/server/src/games.ts
- packages/server/src/rating/rating.ts
- packages/server/src/time-control/time-handler-parallel.ts
- packages/server/src/time-control/timeout.ts
- packages/server/src/users.ts
- packages/shared/.eslintrc.cjs
- packages/shared/src/lib/abstractBoard/helper/PolygonalBoardHelper.ts
- packages/shared/src/lib/graph.ts
- packages/shared/src/variants/baduk.ts
- packages/shared/src/variants/chess.ts
- packages/shared/src/variants/lighthouse/lighthouse.ts
- packages/shared/src/variants/parallel.ts
- packages/shared/src/variants/s_fractional.ts
- packages/vue-client/.eslintrc.cjs
- packages/vue-client/src/components/GameCreation/BoardConfigForms/GridWithHolesBoardConfigForm.vue
- packages/vue-client/src/components/GameCreation/TimeControlConfigForm.vue
This feels like best practice (I had actually assumed this rule was already pulled in via `recommended`)
> add the eqeqeq lint

- packages/shared/src/variant.ts
Fixes #388 
This is one of the core classes used by variant implementers, but it's not always clear how these methods get used by the website.  Hopefully these docs clarify both intention and usage.
> Doc comments on Variant.

- packages/shared/src/index.ts
- packages/shared/src/lib/__tests__/board.test.ts
- packages/shared/src/lib/abstractBoard/boardFactory.ts
- packages/shared/src/lib/abstractBoard/helper/CustomBoardHelper.ts
- packages/shared/src/lib/abstractBoard/helper/__tests__/CustomBoardHelper.test.ts
- packages/shared/src/lib/abstractBoard/index.ts
- packages/vue-client/src/components/GameCreation/BoardConfigForms/BoardConfigForm.vue
- packages/vue-client/src/components/GameCreation/BoardConfigForms/CustomBoardConfigForm.vue
Fixes #111 
Need to do some more testing, but basically this one allows arbitrary adjacency lists
I guess the biggest thing that we need to get right at the beginning is the input format.  Does this seem reasonable?
```
{
"coordinates": [[0, 0], [0, 1], [1, 0], [1, 1]],
"adjacencyList": [[1, 2], [0, 3], [0, 3], [1, 2]]
}
```
> Custom graph

- packages/vue-client/src/components/GameTimer.vue
- packages/vue-client/src/components/GameView/SeatComponent.vue
- packages/vue-client/src/utils/restartable_interval.ts
- packages/vue-client/src/utils/voice-synthesizer.ts
issue: #386 
Here's a prototype for voice count-down using web speech api (thank you for the suggestion @benjaminpjones !)
The count-down only plays for the user who occupies the low on time seat.
In future we can enable users to choose between the available voices (which also means that the count-down can support different languages, depending on which voices are available. When I tested there was English, German and Japanese).
> Low time warning

- packages/shared/src/lib/board_types.ts
- packages/vue-client/package.json
- packages/vue-client/src/components/boards/MulticolorGraphBoard.vue
- yarn.lock
- Add typed package for computing Voronoi Diagram
- use voronoi diagram cells for intersection specific background colors (as in uiTransform).
> add voronoijs, shape click placeholder accordingly

- packages/shared/src/lib/color-utils.ts
- packages/shared/src/templates/pyramid_rules.ts
- packages/shared/src/variants/pyramid.ts
- Add rules description for pyramid.
- Give the pyramid board a different look to highlight the point value difference.
> Pyramid rules

- packages/shared/src/lib/coordinate.ts
- packages/shared/src/templates/drift_rules.ts
- packages/shared/src/variants/drift.ts
- fix last move indicator for drift
- add rules description
> Drift fix last move

- packages/server/migrations/README.md
- packages/server/src/games.ts
- packages/shared/src/variant_map.ts
- packages/shared/src/variants/deprecated/badukWithAbstractBoard.ts
Reverts govariantsteam/govariants#419
> Revert "Remove baduk with abstract board"

- packages/shared/src/index.ts
- packages/shared/src/lib/utils.ts
- packages/shared/src/templates/rengo_rules.ts
- packages/shared/src/variant_map.ts
- packages/shared/src/variants/__tests__/rengo.test.ts
- packages/shared/src/variants/rengo.ts
- packages/vue-client/src/board_map.ts
- packages/vue-client/src/components/GameCreation/RengoConfigForm.vue
- packages/vue-client/src/components/PlayingTable/PolymorphicPlayingTable.vue
- packages/vue-client/src/components/boards/PolymorphicBoard.vue
- packages/vue-client/src/config_form_map.ts
- packages/vue-client/src/playing_table_map.ts
Adds Rengo as higher order variant.
> rengo as higher order variant
