govariantsteam/govariants

package.json, packages/client/package.json, packages/server/package.json, packages/shared/package.json
Specifies jest as the test command (at least for `/shared`).  this should fix the fact that the build is broken.
From the root of the repo you can now run `npm test` or `yarn test` and it will run jest for the shared repo, and any other test scripts we add in the future.
=> Add jest as test script.

packages/server/src/games.ts, packages/server/src/index.ts, packages/server/src/users.ts, packages/shared/src/api_types.ts
This takes raw Mongo calls out of index.ts.  In addition, this lays groundwork for handling both guest and persistent users in a similar way.
- `interface GuestUser`
- `function getUserBySessionId(id)`
- `function createUserWithSessionId(id)`
- `interface PersistentUser`
- `function getUserByName(username)`
- Note: this one may be unnecessary, maybe a more useful function would be `authenticateUser(username, password)`
- `function createUserWithUsernameAndPassword(username, password)`
- `function getUser(id)`
- `function deleteUser(id)`
- `interface UserResponse`
=> User DB abstraction

packages/vue-client/src/components/GameCreationForm.vue
Fixes #72 
Use watch() instead of computed() so that the ref can be modified outside of changes to variant.
=> Fix config entry

packages/vue-client/src/views/GameView.vue
I quickly added the buttons for special moves mainly to bring back the *pass* button, because this allows users to place handicap stones at least manually.
It's not really beautiful, that `makeGameObject()` is called once more solely for accessing the special moves, and more visual cues are necessary, although special moves do show up in the JSON at the bottom of the page. But it's a start.
=> Add buttons for special moves

.gitattributes, packages/vue-client/.eslintrc.cjs
* Let Git "ensure that text files have their line endings normalized". (see https://www.git-scm.com/docs/gitattributes)
* Tell ESLint to "maintain existing line endings" via Prettier's `endOfLine: "auto"` option. (see https://prettier.io/docs/en/options.html)
Why?
Depending on their machine-wide Git settings Windows users might or might not use CRLF instead of LF when Git checks out files to their filesystem and Git might or might not change those CRLFs to LFs when checking in changes.
* Having ESLint interfere with that can cause lots of errors/warnings or lots of changes to files which Git recognizes as such.
* To avoid having CRLF line endings committed, we can tell Git to normalize the line endings for this repository via the `.gitattributes` file.
Caution:
`* text=auto` makes Git …
=> Let Git handle line endings (LF/CRLF) instead of ESLint

packages/shared/src/baduk/baduk.test.ts, packages/shared/src/baduk/baduk.ts
Fixes the issue noted in https://github.com/benjaminpjones/govariants/pull/82#issuecomment-1387325322 and simplifies the `determineController()` function.
=> Fix the counting bug where some borders are open.

packages/vue-client/src/assets/main.css, packages/vue-client/src/components/boards/BadukBoard.vue, packages/vue-client/src/components/boards/BadukBoardAbstract.vue, packages/vue-client/src/components/boards/MulticolorGridBoard.vue, packages/vue-client/src/views/GameView.vue
Fixes #51 
This new CSS should keep the desktop layout more or less the same, but on mobile, the boards will now fit on screen.
=> Responsive board

packages/vue-client/src/views/GameView.vue
If devs are interested in the JSON, it's available in the network tab.  Much cleaner to hide it from the users.
Before/After:
=> Remove the game response JSON from the UI

packages/vue-client/src/components/GameList.vue, packages/vue-client/src/components/GameListItem.vue
Fixes #52 
We could probably get more information in here (players, config etc.) but a board representation is an improvement to the current list of Mongo IDs.
=> Add visual representation of the game to the game list.

.vscode/launch.json, package.json
The `launch.json` file allows to run client *and* server inside VSCode per mouse click (as long as VSCode can find `yarn`, which it does for me only when I run VS Code via a bash terminal, because of how nvm/yarn is setup on my computer).
I've also updated the `start:client` command, to start the `vue-client` package, instead of the react `client` package, which was removed a while ago.
=> Vscode launch

packages/server/src/games.ts, packages/shared/src/abstractAlternatingOnGrid/abstractAlternatingOnGrid.ts, packages/shared/src/badukWithAbstractBoard/badukWithAbstractBoard.ts, packages/shared/src/chess/chess.ts, packages/shared/src/index.ts, packages/shared/src/parallel/parallel.ts, packages/shared/src/utils.test.ts, packages/shared/src/utils.ts
Long needed code health change - we currently have 5 copies of this function.
Doesn't really address the data format issue.  It's now apparent that moves will never really be more than one move even for parallel variants.  I'm wondering if we should just store moves as the output of this function, e.g. `{ player: 1; move: "jk"}`. It's a little less compact, but easy to work with and readable.
=> dedupe getOnlyMove

packages/shared/src/lib/abstractAlternatingOnGrid/abstractAlternatingOnGrid.ts, packages/shared/src/variants/baduk.ts, packages/shared/src/variants/tetris.ts
Most gridded variants are using the Grid class.  Adding this to Baduk will make it easier to perform grid operations, and also it may be easier to generalize to graphs with a similar API.
=> Use Grid in Baduk

packages/shared/src/variants/baduk.ts, packages/vue-client/src/components/boards/BadukBoard.vue
This should also make bugs like #115 more obvious and easier to debug:
=> Show colors on board during scoring.

packages/vue-client/src/components/GameCreation/BadukWithAbstractBoardConfigForm.vue
See [ArsenLapin's comment](https://forums.online-go.com/t/collective-development-of-a-server-for-variants/43682/119)
> I think the two parameters:
> 
> - number of rings;
> - number of nodes per ring
> 
> are inverted for circular go.
> 
> When I ask for 3 rings with 9 nodes per ring I get:
> ![](https://ogs-forums.s3.dualstack.us-east-1.amazonaws.com/original/3X/d/6/d6479807caaa893ff401485672b36c5fce75577a.png)
> 
> Also, the default parameters are 4, 4, which is way too small for any reasonable game.
=> Fixes for circular config form

packages/shared/src/game_map.ts, packages/shared/src/lib/__tests__/grid.test.ts, packages/shared/src/lib/grid.ts, packages/shared/src/variants/__tests__/pyramid.test.ts, packages/shared/src/variants/baduk.ts, packages/shared/src/variants/pyramid.ts, packages/vue-client/src/board_map.ts
Fixes #18.  The visible difference from regular go is very subtle - only the result changes.  In this screenshot, Black wins by 5, whereas White should win by 31.
There are likely some enhancements to highlight that this is a variant, for example showing the weight of each stone on the board somehow or having varying sizes for the score markings.  But this is a start :)
=> Pyramid Go

packages/shared/src/lib/__tests__/grid.test.ts, packages/shared/src/lib/__tests__/group_utils.test.ts
Codifying the `undefined` output of at(), prompted by discussion in #120
=> Add a few tests that demonstrate when Grid.at() returns undefined

packages/shared/src/game_map.ts, packages/shared/src/variants/__tests__/freeze.test.ts, packages/shared/src/variants/freeze.ts, packages/vue-client/src/board_map.ts, packages/vue-client/src/config_form_map.ts
> In addition to the regular Go rules, capturing is forbidden after an atari. That is, if white reduced the number of liberties of any black group to one, black is not allowed to capture stones in the next move. Self-ataris don’t count. This can lead to absolutely crazy variations where both players scramble to play any atari they can find, repeatedly “freezing” their opponent.
https://www.egc2023.de/schedule/atari-go-1-2/
See #132 
https://github.com/govariantsteam/govariants/assets/25233703/91225925-6650-402d-9419-97ee9d3b02ec
=> Add Freeze Go

packages/server/src/games.ts, packages/shared/src/abstract_game.ts, packages/shared/src/api_types.ts, packages/shared/src/lib/abstractAlternatingOnGrid/abstractAlternatingOnGrid.ts, packages/shared/src/lib/abstractBaduk/abstractBaduk.test.ts, packages/shared/src/lib/utils.ts, packages/shared/src/variants/__tests__/baduk.test.ts, packages/shared/src/variants/__tests__/capture.test.ts, packages/shared/src/variants/__tests__/chess.test.ts, packages/shared/src/variants/__tests__/freeze.test.ts, packages/shared/src/variants/__tests__/parallel.test.ts, packages/shared/src/variants/__tests__/phantom.test.ts, packages/shared/src/variants/__tests__/pyramid.test.ts, packages/shared/src/variants/__tests__/tetris.test.ts, packages/shared/src/variants/__tests__/thue_morse.test.ts, packages/shared/src/variants/badukWithAbstractBoard/badukWithAbstractBoard.ts, packages/shared/src/variants/capture.ts, packages/shared/src/variants/chess.ts, packages/shared/src/variants/fractional/fractional.test.ts, packages/shared/src/variants/fractional/fractional.ts, packages/shared/src/variants/freeze.ts, packages/shared/src/variants/parallel.ts, packages/shared/src/variants/phantom.ts, packages/shared/src/variants/thue_morse.ts, packages/vue-client/src/components/GameListItem.vue, packages/vue-client/src/views/GameView.vue
Big PR, but the idea is simple:
```
- abstract playMove(moves: { [player: number]: string }): void;
+ abstract playMove(player: number, move: string): void;
```
Most variants are interested in the player and the move string, and they use `getOnlyMove` to parse these out of the `MovesType`.  Musings in #108 consider changing the format of the moves to reflect what the variant author needs.
In this PR, we parse out `player` and `move` before passing them into `playMove`.  There is no database migration necessary because it does not modify the format of the moves in the database.
**Note to reviewers:** I am mostly interested in your thoughts on the interface; does this API for `playMove` feel better than what we had before?
=> Change the interface of AbstractGame.playMove

packages/server/.eslintrc.cjs, packages/server/package.json, packages/server/src/api.ts, packages/server/src/time-control.ts, packages/shared/.eslintrc.cjs, packages/shared/package.json, packages/shared/src/game_map.ts, packages/shared/src/lib/abstractAlternatingOnGrid/abstractAlternatingOnGrid.ts, packages/shared/src/lib/abstractBaduk/abstractBaduk.test.ts, packages/shared/src/lib/grid.ts, packages/shared/src/variants/__tests__/chess.test.ts, packages/shared/src/variants/baduk.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/PolygonalBoardHelper.ts, packages/shared/src/variants/badukWithAbstractBoard/badukWithAbstractBoard.ts, packages/shared/src/variants/fractional/fractional.ts, packages/shared/src/variants/pyramid.ts, packages/vue-client/.eslintrc.cjs, packages/vue-client/src/components/GameCreation/TimeControlConfigForm.vue, packages/vue-client/src/views/LoginView.vue, packages/vue-client/src/views/RegisterView.vue, yarn.lock
There's starting to be a lot of noise in the linter from all the warnings.  Thought we should make them errors instead.  Turns out the typescript-eslint team was way ahead of me! https://github.com/typescript-eslint/typescript-eslint/issues/5959
I've provided a couple escape hatches since it isn't always straightforward to comply with the linter:
- unused variables are allowed if they are prefixed with an underscore (`_xyz`)
- Especially necessary with overridden methods
- I felt that the underscore is obvious enough, but not too obtrusive
- `any` is allowed in tests
- I would hate to leave out a test just because it broke the type system!
=> Upgrade typescript-eslint and fix lint errors

packages/vue-client/src/components/variant_descriptions/variant_description.consts.ts, packages/vue-client/src/views/GameView.vue
Displays the variant name + a short description in the game view. Also slightly changes the layout of the game view.
=> Add short Variant description in game view

packages/server/src/games.ts, packages/server/src/index.ts, packages/server/src/time-control.ts, packages/server/src/timeout.ts, packages/shared/src/abstract_game.ts, packages/shared/src/lib/utils.ts, packages/shared/src/time_control/time_control.types.ts, packages/shared/src/variants/baduk.ts, packages/shared/src/variants/badukWithAbstractBoard/badukWithAbstractBoard.ts, packages/shared/src/variants/chess.ts, packages/shared/src/variants/fractional/fractional.ts, packages/shared/src/variants/parallel.ts, packages/vue-client/src/components/GameTimer.vue
- add a singleton service for scheduling timeouts (including initialising timeout scheduling for all games on reboot) When a scheduled timeout is resolved, a timeout move is played
- expand the time control handler interface and simplify the move handling as a result
- implement time control handler for parallel moves (note that this will only work as long as we keep the workflow with staged moves)
- Add handling of timeout moves in all variants. For variants with parallel moves, I believe the same handling can be used for resignation (and player dropout in general). But I did not take any other steps to enable resignation in those variants. Also I was not able to test the fractional variant yet, because the client UI for creating a game config with time control is unfortunately still …
=> add singleton service for timeout scheduling

packages/shared/src/__tests__/game_map.test.ts, packages/shared/src/variants/pyramid.ts
Fixes #163 
We had discussed some refactor of the defaut configs/game map, but actually, here is a 4 line fix, and I've also added a test which should prevent this class of bugs in the future.
(I'm still supportive of a refactor, but that takes more care and I wanted to get this variant working again)
=> Support empty config for Pyramid Go

packages/shared/src/game_map.ts, packages/shared/src/index.ts, packages/shared/src/variants/baduk.ts, packages/shared/src/variants/drift.ts, packages/shared/src/variants/freeze.ts, packages/vue-client/src/board_map.ts, packages/vue-client/src/components/GameCreation/DriftGoConfigForm.vue, packages/vue-client/src/config_form_map.ts, packages/vue-client/src/stores/user.ts
This is a prototype for a variant idea:
_Drift Go
After every move, the board shifts in a toroidal-like translation, e.g. the top row becomes the bottom row._
In this implementation, groups that lose their last liberty as a result of the shift are all removed simultaneously and grant no captures.
This is probably not the most efficient implementation (the shift can be represented by only two numbers without re-assigning the whole board), but after testing it, the performance is not bad.
=> prototype for drift go

packages/shared/src/variants/__tests__/polygonal.test.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/PolygonalBoardHelper.ts
This aims to fix a bug of polygonal board where tile connections are missing for size >= 7. As a result overlapping tiles were created, significantly slowing down the rendering of the board (e.g. in the games list, very annoying).
Previously board size 20:
after fix:
Note how the overlapping tiles result in thicker lines.
I also added a test case for this. This change likely breaks old games, but only those affected by the bug (I believe).
As a general note, the whole polygonal board helper could probably be simplified a lot, using this idea with cyclic direction parameter.
=> Bugfix Polygonal board

packages/vue-client/src/assets/base.css, packages/vue-client/src/components/SeatComponent.vue, packages/vue-client/src/views/GameView.vue
merowin and I added a next to play indicator by
- highlighting the seats of the players whose turn it is with a shadow and bolder text
- displaying a list of players to move below or next to the seat list
We also changed the styling of the seat list to make a long list of players wrap to the next column if there's space.
See issue #160
=> Next to play indicator

packages/vue-client/src/assets/base.css, packages/vue-client/src/assets/main.css, packages/vue-client/src/views/GameView.vue
this includes a couple of smaller quality of life fixes:
- players can't play a move while viewing a past round
- fix layout for mobile (I broke that recently with the nav bar pr <- the grid layout in div id=app was counterproductive)
- position round navigation buttons directly below board and add a indicator a.la round 7 / 10
=> cant play move while viewing past round, layout fixes

packages/shared/src/index.ts, packages/shared/src/lib/__tests__/hoshi.test.ts, packages/shared/src/lib/hoshi.ts, packages/vue-client/src/components/boards/BadukBoard.vue
Fixes #24 
Implementation taken from [Besogo](https://yewang.github.io/besogo/).  Note: I only added them to BadukBoard.  It's not to hard to port to other grid boards, but I'd rather focus on unification (#137).
=> Add star points (hoshi).

packages/shared/src/lib/grid.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/BadukBoardAbstract.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/TrihexagonalBoardHelper.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/Vector2D.ts, packages/shared/src/variants/badukWithAbstractBoard/badukWithAbstractBoard.ts, packages/vue-client/src/components/GameCreation/BadukWithAbstractBoardConfigForm.vue
This adds a triangular board with trihexagonal tiling.
size 6:
size 7:
size 8:
size 19:
=> Board with trihexagonal tiling

packages/shared/src/lib/abstractBaduk/badukIntersection.ts, packages/shared/src/lib/abstractBoard/boardFactory.ts, packages/shared/src/lib/abstractBoard/intersection.ts
I love that Fractional (and AbstractBaduk) work with arbitrary graphs! For the Rhombitrihexagonal board, it seems that the intersection ids were not set after conversion. This is an attempt to fix it.
=> set id of intersections in createRthBoard

packages/server/src/games.ts, packages/server/src/time-control/timeout.ts, packages/vue-client/src/components/GameTimer.vue
This tries to simplify and reduce duplicated code in the timeout service as we briefly talked about in https://github.com/govariantsteam/govariants/pull/185
My approach is to split the playMove method into two parts: 
- playMove does the user specific validations and then calls ...
- handleMoveAndTime which does the rest (validate the move, update time control, schedule timeouts, update db game, notify clients)
Then I can reuse this second method in the timeout service, where we should skip the user specific validation (if the seat was vacated in the meantime, it still times out).
I've also included another fix, because I noticed this when testing: Over a couple of minutes, the visual timer was running a bit behind. I believe this was due to the fact that I set an interval which decreases …
=> refactor play move, fix timer display delay

packages/vue-client/README.md
Removes the references to npm in readme file
The other change was automatically made, but I think its ok.
=> remove npm from readme

packages/vue-client/package.json, packages/vue-client/src/App.vue, packages/vue-client/src/assets/base.css, packages/vue-client/src/assets/main.css, packages/vue-client/src/components/UserNav.vue, yarn.lock
An attempt to improve the nav bar for mobile. It collapses the nav bar when the screen is small and uses a hamburger menu instead. This will make it so we can safely add more stuff to the nav bar in the future :-)
Work in progress - layout and styles are basically done, menu toggle function still missing.
Before:
Current:
=> Better navbar for mobile

packages/server/package.json, yarn.lock
For some reason, the `launch` script tries to build tests and Heroku doesn't look at dev dependencies 🤔  so the server crashed with these logs:
```
2024-03-05T05:36:58.861553+00:00 heroku[web.1]: Starting process with command `yarn workspace @ogfcommunity/variants-server launch`
2024-03-05T05:37:04.807589+00:00 app[web.1]: src/time-control/__tests__/sequential.test.ts(14,1): error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
2024-03-05T05:37:04.807976+00:00 app[web.1]: src/time-control/__tests__/sequential.test.ts(15,3): error TS2582: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i …
```
=> fix stuff?

packages/shared/src/variants/__tests__/quantum.test.ts, packages/shared/src/variants/quantum.ts, packages/vue-client/src/components/boards/QuantumBoard.vue
From Zi
> We did find a minor issue, i.e., the quantum pairs should live or die together, so once they are removed, the paired positions are still paired, meaning if a new stone is placed on one board in one of the quantum positions, it should also appear in the paired position on the other board.
---
This update actually simplifies the code because we no longer need to break entanglements.
- Move all quantum logic out of the helper class (and rename to `BadukHelper`)
- Represent quantum stones with a 1D 2-element array, instead of a 2D array
- Fix the quantum "reviving" of stones
- Add two tests
=> Quantum fix

packages/vue-client/src/components/boards/QuantumBoard.vue
The 2:1 aspect ratio is always going to be difficult, but currently, the boards are half the size they could be based on height.  There is no change on narrow screens.
Before:
After:
=> Improve layout for quantum boards.

packages/server/src/games.ts, packages/server/src/time-control/__tests__/sequential.test.ts, packages/server/src/time-control/time-handler-parallel.ts, packages/server/src/time-control/time-handler-sequential.ts, packages/shared/src/variants/baduk.ts, packages/shared/src/variants/badukWithAbstractBoard/badukWithAbstractBoard.ts, packages/shared/src/variants/capture.ts, packages/shared/src/variants/parallel.ts, packages/vue-client/src/components/GameTimer.vue
1. removes the timeout button (my bad)
2. pass is not allowed in capture variant
3. fix some issues with time handling:
Game ending moves need to be handled, otherwise the winning players time keeps running.
If A player times out, its time is set to 0, so it is displayed correctly.
=> Remove timeout button, Some time handling fixes

packages/vue-client/src/components/GameTimer.vue, packages/vue-client/src/components/SeatComponent.vue
The logic gets a lot simpler if we can assume time_control is not null.  Anyway, `<GameTimer time_control="null">` isn't very meaningful.  So instead we type it as non-null and guard it with a v-if.
Some other small changes: make more use of computed variables, and try to remove variables while keeping the same functionality.
Motivation: this should help a bit with #233
=> Clean up the GameTimer Vue component

packages/server/src/time-control/__tests__/parallel.test.ts, packages/server/src/time-control/__tests__/time-handler-utils.test.ts
In #223 , there will be many code changes to the time handlers in order to use the `TimeControl` classes. Hopefully, there will be no functional changes for existing time control types `Fischer` and `Absolute`. Additional test coverage will increase my confidence with these modifications.
---
Testing:
```
$ cd packages/server
$ yarn test --coverage
PASS  src/time-control/__tests__/time-handler-utils.test.ts
✓ initialState (Absolute) (5 ms)
✓ makeTransition (Absolute) (2 ms)
✓ makeTransition: timeout (Absolute) (3 ms)
✓ makeTransition: timeout (Fischer) (3 ms)
✓ makeTransition: (Uncapped Fischer) (3 ms)
✓ makeTransition (Invalid) (6 ms)
✓ msUntilTimeout (Absolute) (2 ms)
✓ msUntilTimeout (Absolute) (2 ms)
PASS  src/time-control/__tests__/parallel.test.ts
✓ initialState (Fischer) (4 ms)
✓ …
```
=> Test parallel and shared handler code

packages/server/src/games.ts, packages/server/src/time-control/__tests__/parallel.test.ts, packages/server/src/time-control/__tests__/sequential.test.ts, packages/server/src/time-control/__tests__/time-handler-utils.test.ts, packages/server/src/time-control/time-handler-parallel.ts, packages/server/src/time-control/time-handler-utils.ts, packages/shared/src/api_types.ts, packages/shared/src/time_control/__tests__/time_control_systems.test.ts, packages/shared/src/time_control/index.ts, packages/shared/src/time_control/time_control.types.ts, packages/shared/src/time_control/time_control.utils.ts, packages/shared/src/time_control/time_control_systems.ts, packages/vue-client/src/components/GameCreation/TimeControlConfigForm.vue, packages/vue-client/src/components/GameTimer.vue, packages/vue-client/src/components/SeatComponent.vue, packages/vue-client/src/views/GameView.vue
Update: I've plugged it in, and both the old and new time controls seem to work as expected!  Good test suite on the handlers too - helped me debug a lot of issues on my first pass.
Sorry it's such a big diff.  Hopefully the break down of the commits help to understand what's going on.  I'm also going to leave this open for a while so I can test some more, but publishing now because it seems ready.
---
This is a proposal for a generic interface for additional time controls.  I have not plugged it into the code yet, but I hope it demonstrates a strategy that we can use to onboard Byoyomi, Simple and Canadian to reach parity with OGS.
I am opening this PR as draft to make sure I don't collide with anyone and also gather early feedback, but I plan to do the following before marking "Ready": …
=> Add Byo-Yomi, Canadian, and Simple time controls

packages/server/src/time-control/__tests__/time-handler-utils.test.ts, packages/server/src/time-control/time-handler-parallel.ts, packages/server/src/time-control/time-handler-sequential.ts, packages/server/src/time-control/time-handler-utils.ts, packages/server/src/time-control/timeout.ts
issue: https://github.com/govariantsteam/govariants/issues/231
This should fix the basic timeout scenario for parallel move variants. The scenario where multiple people timeout at almost the same time does not get fixed by this.
Remove the move from the transition. Due to how the parallel move time handler works currently (we don't consider the moves except for the move that triggers the round transition), we can't handle specific moves like timeout in the transition.
Remark: The deleted code parts are not important for the timeout scheduling (as a timeout move was already played, when this is relevant).
I've also added a check in the parallel handler to ensure that stagedMoveAt is set when transition is called.
=> fix transition for parallel time handler

packages/server/package.json, packages/server/src/index.ts, packages/server/src/socket_io.ts, yarn.lock
I wasn't getting socket messages in my dev environment, and it's because of a CORS mismatch.  I only recently noticed because I was looking at time control, where socket is necessary to receive the timeout event on the client.  The current value is IPv4 `127.0.0.1:5173`, but on my machine (Mac), it's the IPv6 `[::1]:5173`.
1) Sets multiple CORS origins so that development works okay in all environments, regardless of whether a user visits `localhost:5173`, `127.0.0.1:5173`, or `[::1]:5173`.
- @merowin fyi - this PR shouldn't break your dev environment, but just in case.  I know `"127.0.0.1:5173"` has been working best for you
2) Remove `app.use(cors({ origin: LOCAL_ORIGIN, ...))`
- Since `LOCAL_ORIGIN` has been "wrong" this whole time, it seems clear this line isn't needed
- @JonKo314 let …
=> CORS stuff

package.json, packages/shared/package.json, packages/shared/scripts/create-new-variant.mjs, packages/shared/src/variants/template/variant.test.ts.njk, packages/shared/src/variants/template/variant.ts.njk, yarn.lock
This is a bit experimental - I think it could be nice to have a way to generate boilerplate for new variants.  I don't know if this offers a ton of value on top over just copy+paste, but I'd like to try it out in case it's useful.
How to use:
- From the packages/shared directory, run `yarn new-variant variant_name` to generate code.
- A simple test is also generated, which can be run with `yarn test variant_name`
```
$ cd packages/shared
$ yarn new-variant my_new_variant                   
Directory copied and templates replaced successfully.
$ yarn test my_new_variant
PASS  src/variants/__tests__/my_new_variant.test.ts
✓ Play a game (5 ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.48 s, estimated 1 s
Ran all test suites matching …
```
=> Variant templates

packages/vue-client/src/components/boards/BadukBoard.vue, packages/vue-client/src/components/boards/MulticolorGridBoard.vue, packages/vue-client/src/components/boards/board_utils.ts
The specific error was: `toRefs() expects a reactive object but received a plain one`. I believe it's because props.config is not reactive even though props is reactive.  I also made `positions` a computed property.
=> Fix some reactivity issues in Grid boards.

Procfile
In attempt to address #37, I will do the following in order:
1) Copy the procfile into root (this PR)
2) Remove the [Multi Procfile buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-multi-procfile)
3) Delete `server/Procfile`
---
From Heroku docs:
> The Procfile must live in your app’s root directory. It does not function if placed anywhere else.
The only reason it's working currently is the Multiprocfile buildpack looks at a `PROCFILE` environment variable. However, we aren't using multiple Procfiles anymore, so this is superfluous.
=> Copy Procfile into the root directory.

packages/server/package.json
Semantically, `tsc` is definitely the "build" command for the server.  The motivation for splitting this out is #97 - it makes sense to run "yarn build" as part of PR checks, but doesn't make as much sense to run "launch".
If you're wondering why I didn't update the Heroku config, it's because [Heroku runs `yarn build` automatically](https://devcenter.heroku.com/changelog-items/1573) 🤞
=> [server] Separate "build" and "launch" scripts.

packages/vue-client/package.json, packages/vue-client/src/components/NavButtons.vue, packages/vue-client/src/views/GameView.vue, yarn.lock
Modularity is generally a good thing, and I am specifically looking to reduce code duplication as I create a separate "client-only" game page (check out the [variant-demo branch](https://github.com/govariantsteam/govariants/tree/variant-demo) if you're interested!).
- Upgrade Vue: 3.4 has a nice function [`defineModel()`](https://vuejs.org/api/sfc-script-setup.html#definemodel)
- Split out `<NavButtons />`
Tested manually, no changes in behavior that I noticed.
=> Split out NavButtons into a separate component

packages/server/package.json, packages/server/src/index.ts
Noticed some log spam following #244:
While there may be some way to synchronize the shared and server reload scripts, I think the easiest is to put a small delay (500 ms) on server reloads.
=> Delay nodemon reloads

packages/shared/src/game_map.ts, packages/shared/src/index.ts, packages/shared/src/lib/__tests__/board.test.ts, packages/shared/src/lib/abstractBoard/boardFactory.ts, packages/shared/src/variants/__tests__/quantum.test.ts, packages/shared/src/variants/baduk.ts, packages/shared/src/variants/baduk_utils.ts, packages/shared/src/variants/drift.ts, packages/shared/src/variants/keima.ts, packages/shared/src/variants/pyramid.ts, packages/shared/src/variants/quantum.ts, packages/vue-client/src/board_map.ts, packages/vue-client/src/components/GameCreation/BadukConfigForm.vue, packages/vue-client/src/components/GameCreation/DriftGoConfigForm.vue, packages/vue-client/src/components/boards/BadukBoard.vue, packages/vue-client/src/components/boards/BadukBoardSelector.vue, packages/vue-client/src/components/boards/BadukGraphBoard.vue, packages/vue-client/src/components/boards/MulticolorGraphBoard.vue, packages/vue-client/src/components/boards/QuantumBoard.vue
- take out the baduk adapter class
- some more refactoring so the variants can work with graph boards
- add components for graph boards in the vue-client that work with baduk and the board factory
- make it so Freeze, Quantum have boards that render the graph boards (they have their own components)
- add game config input forms for variants that now support the new patterns.
- Figure out what to do with Annotations on the board (I copied the Multicolored Grid board and made it work for the graphs).
It's already working for the most part. Here is variant Tetris on a rhombitrihexagonal board:
I had some problems with backwards compatibility at first, but I think that I sorted those out.
=> add components for new board patterns that work with baduk

packages/vue-client/src/components/GameCreation/BadukConfigForm.vue, packages/vue-client/src/components/GameCreation/BoardConfigForms/BoardConfigForm.vue, packages/vue-client/src/components/GameCreation/BoardConfigForms/CircularBoardConfigForm.vue, packages/vue-client/src/components/GameCreation/BoardConfigForms/GridBoardConfigForm.vue, packages/vue-client/src/components/GameCreation/BoardConfigForms/RhombitrihexagonalBoardConfigForm.vue, packages/vue-client/src/components/GameCreation/BoardConfigForms/SierpinskyBoardConfigForm.vue, packages/vue-client/src/components/GameCreation/BoardConfigForms/TrihexagonalConfigForm.vue, packages/vue-client/src/components/GameCreation/GridBadukConfigForm.vue, packages/vue-client/src/components/boards/MulticolorGraphBoard.vue, packages/vue-client/src/config_form_map.ts
This adds components for input forms for the various board configs. I tried to streamline these components by having one dedicated component for each board pattern.
With this it will be possible to create and play games with the new board patterns for variants baduk, phantom, capture, tetris, thue-morse, and one-color.
For variants freeze and quantum it should not be too much work to also enable this, but since these have their own board component, I'd like to do this in a separate PR.
It's worth noting that there's a couple of possible improvements that I've ignored for now.
1.) The graph board component doesn't use the annotations yet.
2.) At the moment, the newly added config input forms don't use the default config as defined by the variant itself, but their own default config.
=> add board config input form components

packages/shared/src/variants/quantum.ts, packages/vue-client/src/components/boards/QuantumBoard.vue, packages/vue-client/src/config_form_map.ts
This adds the graph boards to quantum go.
I thought about the possibility of storing the moves for graph boards also in SGF format, to simplify the logic here. But I decided against it, one reason being that we should stay consistent (in my opinion).
=> graph boards for quantum

packages/shared/src/deprecated_variants.ts, packages/shared/src/game_map.ts, packages/shared/src/lib/__tests__/board.test.ts, packages/shared/src/variants/badukWithAbstractBoard/badukWithAbstractBoard.ts, packages/vue-client/src/components/boards/BadukBoardAbstract.vue
With the recent addition of graph boards to Baduk and inheriting variants, I believe that we should deprecate the old variant BadukWithAbstractBoard.
For this purpose I added a function that maps a config of BadukWithAbstractBoard to a config for Baduk, and created a (sort-of) constructor function that we can use in the game_map. So old games of this variant should still work, and we can remove the class.
Also added a list for deprecated variants, s.t. these can't be selected in the game creation form.
=> Deprecate variant Baduk with abstract board

packages/server/src/api.ts, packages/server/src/games.ts, packages/server/src/index.ts, packages/shared/src/api_types.ts, packages/shared/src/variants/fractional/fractional.test.ts, packages/shared/src/variants/fractional/fractional.ts, packages/vue-client/src/components/boards/FractionalBoard.vue, packages/vue-client/src/views/GameView.vue
- Add server endpoints for getting (initial-) game information. Importantly this does not include the moves array, instead the view state defining properties. So the received information can depend on the selected seat.
- add a subscription based system for sending the state to the appropriate clients when a move is made. I believe this does not fully work yet, unfortunately.
- major change of the game view page to work with the new structures
- I did not remove the endpoint that returns the game moves array. I'm not sure if its used by the game list. We may need to change that too, to make sure that hidden information can't leak.
- I tested (among other things) the staged moves of parallel. At the moment they don't show up in the game view unfortunately, I don't know the reason yet.
- In …
=> send state via api instead of all moves

packages/shared/src/lib/abstractBaduk/abstractBaduk.ts, packages/shared/src/lib/abstractBaduk/badukIntersection.ts, packages/shared/src/lib/abstractBoard/boardFactory.ts, packages/shared/src/lib/abstractBoard/intersection.ts, packages/shared/src/lib/graph.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/BadukBoardAbstract.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/CircularBoardHelper.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/PolygonalBoardHelper.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/SierpinskyBoard.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/TrihexagonalBoardHelper.ts, packages/shared/src/variants/badukWithAbstractBoard/abstractBoard/intersection.ts, packages/shared/src/variants/fractional/fractional.test.ts, packages/shared/src/variants/fractional/fractional.ts, packages/vue-client/src/components/boards/FractionalBoard.vue, packages/vue-client/src/components/boards/MulticolorGraphBoard.vue
fixes: #261 
Instead of using an ID in the intersection class, use its index in the intersection array as unique identifier. This ensures consistency with the variant implementation, which use the graph class.
=> remove intersection id

packages/vue-client/src/components/boards/BadukBoard.vue, packages/vue-client/src/components/boards/FractionalBoard.vue, packages/vue-client/src/components/boards/MulticolorGraphBoard.vue, packages/vue-client/src/components/boards/MulticolorGridBoard.vue, packages/vue-client/src/components/boards/QuantumBoard.vue
fixes #257
There were conflicting definitions of width and height of the board svg element. Note that GameView.vue has the following style definition:
```
@media (min-width: 664px) {
.board {
width: var(--board-side-length);
height: var(--board-side-length);
}
}
```
Additionally, the board implementations had width and height set to 100%, which caused the nav-buttons and variant description to overflow into the next grid element.
Previously:
After:
=> fix board dimensions layout

packages/vue-client/src/views/GameView.vue
Most variants don't support file download, so we can hide the button for them:
=> Hide download button if it's not supported

.github/workflows/node.js.yml
Github no longer supports node v16, moving to 20. (I think Heroku is using that anyway)
=> Upgrade node version used in GH actions

packages/shared/src/variants/fractional/fractional.ts, packages/vue-client/src/components/boards/FractionalBoard.vue
Adds an indicator of last rounds moves in variant fractional. Example:
=> indicator of last moves in variant fractional

packages/vue-client/src/views/GameView.vue
This is just a demonstration of how the view can be improved, by relying more on Vue's reactivity system.
- Split up watchEffect, so certain effects run less often
- Don't perform any side-effects in `setPlayingAs`
- remove `unsubscribeAllSeats` - I felt this was a heavy-handed approach, since we really only need to unsub the currently subscribed seat
- Ensure we unsubscribe from the "unseated" topic (i.e. `game/${id}`
- This last bullet is actually a change in functionality, and means we aren't always sending the `seat: null` "move" message
=> Better application of reactivity in the GameView page

packages/vue-client/src/components/boards/FractionalBoard.vue
This fixes a problem that can occur with the last move indicator in fractional when a played stone gets immediately captured. Then previously the last move indicator was positioned in front of the click placeholder, making it impossible to play a move at that position.
To fix this, I changed the order of elements. Had to adjust the v-else to a v-if with negated condition.
=> change order of last move indicator and click placeholder

packages/shared/src/variants/baduk.ts, packages/shared/src/variants/freeze.ts, packages/vue-client/src/components/boards/FreezeGoBoard.vue, packages/vue-client/src/config_form_map.ts
Refactor Freeze board component to enable the graph boards.
This is an addendum to the rework where we enabled graph boards for baduk.
=> enable graph boards for freeze

packages/vue-client/src/playing_table_map.ts, packages/vue-client/src/views/GameView.vue
issue #134
I added `playing_table_map` that is a copy of `board_map`, and use this new map in GameView. Notably the GamesList still uses `board_map`.
Should be no functional change yet. This PR is to discuss whether we want this structural change.
=> add playing table map

packages/shared/src/variants/capture.ts, packages/shared/src/variants/freeze.ts, packages/shared/src/variants/keima.ts, packages/shared/src/variants/one_color.ts, packages/shared/src/variants/phantom.ts, packages/shared/src/variants/quantum.ts, packages/shared/src/variants/tetris.ts, packages/shared/src/variants/thue_morse.ts
Problem: lots of this:
```
defaultConfig: Baduk.defaultConfig,
getPlayerColors: Baduk.getPlayerColors,
// In the future
sanitizeConfig: Baduk.sanitizeConfig,
anotherProperty: Baduk.anotherProperty,
```
Not sure if this is the way, but I'm looking to prevent a bunch of copied code for Baduk-based variants.  Would love your thoughts.
=> Use badukVariant values by default.

packages/shared/src/index.ts, packages/shared/src/variants/s_fractional.ts, packages/shared/src/variants/thue_morse.ts, packages/vue-client/src/components/GameView/PlayerSymbol.vue, packages/vue-client/src/components/MoveSequenceDisplay.vue, packages/vue-client/src/components/PlayingTable/SFractionalTable.vue, packages/vue-client/src/components/PlayingTable/ThueMorseTable.vue, packages/vue-client/src/playing_table_map.ts, packages/vue-client/src/views/GameView.vue
Here I added a component that can be used to display upcoming moves for variants with an unusual move sequence. I added a white shadow to stones displayed (also in the PlayerSymbol) to create contrast with dark-theme.
=> Display upcoming moves in Thue-Morse and SFractional

packages/server/src/games.ts, packages/shared/src/__tests__/game_map.test.ts, packages/shared/src/variant.ts, packages/shared/src/variant_map.ts, packages/shared/src/variants/__tests__/baduk.test.ts, packages/shared/src/variants/baduk.ts, packages/shared/src/variants/badukWithAbstractBoard/badukWithAbstractBoard.ts, packages/shared/src/variants/baduk_utils.ts, packages/shared/src/variants/capture.ts, packages/shared/src/variants/freeze.ts, packages/shared/src/variants/keima.ts, packages/shared/src/variants/one_color.ts, packages/shared/src/variants/phantom.ts, packages/shared/src/variants/pyramid.ts, packages/shared/src/variants/quantum.ts, packages/shared/src/variants/tetris.ts, packages/shared/src/variants/thue_morse.ts
Currently, we sanitize configs *inside* the Game objects, but there are other places that access configs.  (e.g. GameView).  Let's sanitize outwardFacingGame so that we can always assume we have a modern config.
=> Sanitize config as soon as it comes from db.

packages/vue-client/.eslintrc.cjs, packages/vue-client/src/components/GameCreation/BadukConfigForm.vue, packages/vue-client/src/components/GameCreation/BadukWithAbstractBoardConfigForm.vue, packages/vue-client/src/components/GameCreation/DriftGoConfigForm.vue, packages/vue-client/src/components/GameCreation/GameCreationForm.vue, packages/vue-client/src/components/GameCreation/ParallelGoConfigForm.vue, packages/vue-client/src/components/GameCreation/TimeControlConfigForm.vue, packages/vue-client/src/components/GameView/SeatComponent.vue, packages/vue-client/src/components/GamesFilterForm.vue, packages/vue-client/src/views/AboutView.vue, packages/vue-client/src/views/LoginView.vue, packages/vue-client/src/views/RegisterView.vue, packages/vue-client/src/views/RulesView.vue
Inspired by  #298, `scoped` seems to be best practice.  Let's enforce it everywhere.
=> Add enforce-style-attribute lint rule

packages/shared/src/index.ts, packages/shared/src/variants/__tests__/keima.test.ts, packages/shared/src/variants/baduk.ts, packages/shared/src/variants/keima.ts, packages/vue-client/src/components/boards/KeimaBoard.vue
Here are some change proposals to variant Keima based on the poll + discussion that we had here: [https://forums.online-go.com/t/collective-development-of-a-server-for-variants/43682/154](url)
- Validate and throw if there are no legal keima follow-up moves.
- Players can pass or play one keima, but they can't place a single stone and then pass.
This rules makes it so the variant basically can't be played on boards <= 2x2, but I only just realised that I should include a check for that.
=> Validate if there are follow-up moves in Keima variant

packages/vue-client/src/components/boards/BadukGraphBoard.vue, packages/vue-client/src/components/boards/MulticolorGraphBoard.vue, packages/vue-client/src/components/boards/MulticolorGridBoard.vue, packages/vue-client/src/components/boards/SFractional/SFractionalGraphBoard.vue, packages/vue-client/src/components/boards/SFractional/SFractionalGridBoard.vue, packages/vue-client/src/components/boards/ScoreMark.vue, packages/vue-client/src/components/boards/board_types.ts
This adds score boards to multicolor boards. ~~Only unicolor score because I did not know how to best display a multicolor score marking (rectangle), but I believe for all our current variants, this is sufficient.~~ <- added multicolor score markings
Also I didn't implement the mapping from game state in all boards - I'm thinking we should probably try to reduce the number of board implementations, I'm just unsure how.
This is one step for #137
On graph boards it looks a bit funny, maybe due to rounding problems (?)
=> add score board in multicolor boards

packages/vue-client/src/components/boards/MulticolorGridBoard.vue
It's related to https://github.com/govariantsteam/govariants/issues/137, wherein we'd like to replace all boards with the Multicolor ones.
=> Star points for MulticolorGridBoard

packages/server/src/games.ts, packages/vue-client/src/views/GameView.vue
This aims to fix a time control bug that unfortunately I introduced with the game state changes.
The problem is when a move is played, the state sent does not include the time control object. As a consequence the clock does not display the times.
I've also made it so the game state map does not include the time control object any more ,for clarity and potentially saving memory space. I think even if users browse through the game history, its ok if we display the current times.
=> fix bug where time control is undefined

packages/vue-client/src/assets/main.css, packages/vue-client/src/components/GameCreation/BadukConfigForm.vue, packages/vue-client/src/components/GameCreation/BadukWithAbstractBoardConfigForm.vue, packages/vue-client/src/components/GameCreation/BoardConfigForms/BoardConfigForm.vue, packages/vue-client/src/components/GameCreation/DriftGoConfigForm.vue, packages/vue-client/src/components/GameCreation/GameCreationForm.vue, packages/vue-client/src/components/GameCreation/ParallelGoConfigForm.vue, packages/vue-client/src/components/GameCreation/TimeControlConfigForm.vue, packages/vue-client/src/views/GameView.vue, packages/vue-client/src/views/VariantDemoView.vue
- give 100% width to all input fields in the game creation form (I believe it was originally my mistake to limit the width).
- give the "Create Game"-button 100% width and vertical padding
- add small gap in the column
- enable in-text line breaks in short variant description (the baduk short description looks weird ever since I added it).
=> Game creation form style improvements

packages/vue-client/src/components/GameListItem.vue
In the games list, this disables hover (and other pointer events) on the board by wrapping it with a div with a style for this purpose. Clicking the outer link still works and navigates to the Game page.
issue: #107 (although just for the games list)
=> disable hover in games list

packages/vue-client/.eslintrc.cjs, packages/vue-client/src/components/GameCreation/TimeControlConfigForm.vue, packages/vue-client/src/components/GameTimer.vue
Now linter can catch the `@ogfcommunity/variants-shared/src/path/to/file` imports!
=> Add lint rule to prevent /src/ imports and fix instances.

packages/shared/src/variants/__tests__/s_fractional.test.ts, packages/shared/src/variants/s_fractional.ts
This fixes the score board of SFractional. Previously it didn't mark or count the stones on the board, now it does.
=> Fix area scoring of SFractional

packages/vue-client/src/views/VariantDemoView.vue
This makes it so the upcoming moves display works in the demo board.
Remark about the displayed_round: Not all variant view components have this prop, and as a result I get this warning:
But in testing, it didn't seem to break anything (also in the game view component).
=> pass round to playing table in demo

packages/shared/src/lib/grid_compat.ts, packages/vue-client/src/components/boards/QuantumBoard.vue
https://github.com/govariantsteam/govariants/pull/327#discussion_r1842799084
The major benefit is that we're able to remove some duplicate codepaths for Grid and Graph boards.  I did fudge types quite a bit, so I'm open to ideas on improvement, but overall, it works, and I think the reduction in code (~50 lines) is worth it.
Tested: both grid and graph boards
Forgot to screnshot grid, but I promise I tested that too :)
=> Migrate QuantumBoard to DefaultBoard

packages/vue-client/src/App.vue, packages/vue-client/src/assets/main.css, packages/vue-client/src/views/AboutView.vue, packages/vue-client/src/views/ComponentView.vue, packages/vue-client/src/views/GameView.vue, packages/vue-client/src/views/HomeView.vue, packages/vue-client/src/views/LoginView.vue, packages/vue-client/src/views/RegisterView.vue, packages/vue-client/src/views/RulesView.vue, packages/vue-client/src/views/VariantDemoView.vue
- Pull pageWrapper into each View
- in Home View, move the games list into the right column
- in Game View, add Divs for left and right column
With the first change, it is easier for each view to define its layout individually. This also helps with the second change.
In the right column, the games list is easier accessible on desktop. For mobile it moves below as usual.
In the Game view, previously each added html element was positioned as a new element in the grid layout, resulting in elements being positioned seemingly randomly. I think it makes more sense to have a left- and right column that encapsulate all other elements.
=> Layout changes

packages/shared/src/variant_map.ts, packages/vue-client/src/App.vue, packages/vue-client/src/assets/base.css, packages/vue-client/src/assets/main.css, packages/vue-client/src/router/index.ts, packages/vue-client/src/utils/format-utils.ts, packages/vue-client/src/views/RulesListView.vue, packages/vue-client/src/views/RulesView.vue
This adds a new view that is linked to in the NavBar and has links to the rules page for variants with a (detailed) rules description.
Also I've added the demo board to the rules view as proposed in https://github.com/govariantsteam/govariants/issues/112
I wasn't able to make sure that the demo board fits, so I made its container scrollable on overflow.
=> Rules List

packages/shared/src/lib/abstractBaduk/abstractBaduk.ts, packages/shared/src/variants/fractional/fractional.test.ts
Wrong intersection indices were compared. E.g. the surrounded corner stone in the test was not checked, because it was `changedIntersection[7]` and `AbstractBaduk`'s `this.intersection[7]` was already checked as a part of the long black chain.
This fixes the [bug mentioned on OGS forums](https://forums.online-go.com/t/parallel-fractional-go-game-4/53434/100) of Game 4's round 16.
=> fix liberty check for fractional go

packages/server/src/api.ts, packages/server/src/users.ts, packages/shared/src/api_types.ts, packages/vue-client/src/requests.ts, packages/vue-client/src/router/index.ts, packages/vue-client/src/stores/user.ts, packages/vue-client/src/views/UserView.vue
This adds the admin role and one elevated privilege: the ability to make another user an admin.
[Screencast_20241123_232459.webm](https://github.com/user-attachments/assets/ad96e336-901f-4a88-9231-f76dc22e4e03)
A couple required, but not directly related changes:
- Created User page, where we add the "Make Admin" button
- Fixed up some User types:
- `id` should be required in `UserResponse`, except for DB code
- Some instances of `User`changed to `UserResponse`.
- I think these are generally interchangeable (except for the optional id issue).  I should follow up to merge the two.
=> Admin role

.husky/pre-commit, package.json, yarn.lock
Fixes #290 
Git hooks is something I find personally useful, and I notice a lot of "fix lints" commits so I wonder if it would help others too.  If you think this would be a bother, let me know and we can make it opt-in (likely by removing it from the "postinstall" script.)
A couple things to know about using husky:
- If we call it in "postinstall" it will be propagated to all developers during `yarn` install
- Devs can add `-n`/`--no-verify` flag during `git commit` to skip the check
=> Add husky (git commit hooks)

.husky/pre-commit, package.json, yarn.lock
Reverts govariantsteam/govariants#348
Heroku didn't like that. It's unclear from the logs what about this it didn't like though. Maybe postinstall or devDependencies.
=> Revert "Add husky (git commit hooks)"

packages/vue-client/src/views/AboutView.vue
I added the link to Element (for inviting people) - though I'm not sure if this is the best URL for this purpose.
=> add link to element

packages/vue-client/src/components/boards/QuantumBoard.vue
fixes #358 
Reason for the bug is that previously empty intersection was represented as undefined, now by empty array, and we used to call `colors?.push("green")` which used to only add green when the position is already occupied. So I added a function that does this for the new representation.
=> fix display bug in quantum

.husky/pre-commit, package.json, packages/server/package.json, packages/shared/package.json, packages/vue-client/package.json, yarn.lock
pre-commit check currently:
- is slow (>30s on my machine)
- checks all changes, even if they aren't staged
- performs write operations
- Use [lint-staged](https://github.com/lint-staged/lint-staged?tab=readme-ov-file#configuration)
- Just lint, skip tests
- Run read-only operations (e.g. `--check` instead of `--write`)
On my machine (Intel Core i5-8250U CPU @ 1.60GHz), I have these times after staging changes for a single file:
- `yarn lint`: ~14s
- `yarn test`: ~20s
- `yarn lint-staged`: ~6s
Therefore, we have a roughly 5x speedup, though it will depend heavily on the machine and staged files.
=> Optimize pre-commit

packages/server/src/api.ts, packages/server/src/games.ts, packages/vue-client/src/components/GameView/SeatComponent.vue, packages/vue-client/src/views/GameView.vue
This adds a little toggle on the games page for admins that allows them to use special powers. It's off-by-default, so admins can enjoy games as normal users.  This PR also adds the power to kick a user from their seat.
https://github.com/user-attachments/assets/2c7cd98b-c80e-487d-af68-ea66066309f1
=> Add admin mode to games page, and allow admins to kick users

packages/server/src/api.ts, packages/server/src/index.ts, packages/vue-client/package.json, packages/vue-client/src/requests.ts, packages/vue-client/src/views/UserView.vue, yarn.lock
Basically what the title says.  Additionally, I pulled in the [sweetalert2](https://sweetalert2.github.io) library.  This gives us ability to launch more advanced modals than `window.alert()`, which was necessary for the additional verification in the User deletion flow.
0) Log in as admin
1) Click "Delete User"
2) Enter user's name as a safeguard
3a) On failure, inform the admin
3b) On success, inform the admin, then return home
=> Allow admins to delete users

packages/shared/src/lib/abstractBoard/helper/SierpinskyBoard.ts
I am happy to see that somebody played on the Sierpinsky board 😄 
I noticed that the stones overlap:
This PR fixes it:
=> fix distances of sierpinsky board

packages/shared/src/variants/baduk.ts, packages/shared/src/variants/baduk_utils.ts, packages/shared/src/variants/s_fractional.ts, packages/vue-client/src/components/IntersectionAnnotation.vue, packages/vue-client/src/components/boards/MulticolorGraphBoard.vue
Issue: #137 
- circle annotation uses mix-blend-mode: difference
- enable the annotation in variants baduk, sfractional
- fix annotation in graph board
=> Last move indicator in UI transform

packages/shared/src/variants/baduk_utils.ts
Fixes technical debt that I left behind, see https://github.com/govariantsteam/govariants/pull/371#discussion_r1911865871
Makes the function types more explicit.
I would like to avoid the type assertions in the implementation function, but I don't know how.
=> more explicit types of board map functions

packages/shared/src/variants/fractional/fractional.ts
Currently, we list every player in `nextToPlay` because, technically, all players may move.  I propose we exclude staged players since they are not required to play again in the round.  Motivation: I believe this will be useful in [Forums game](https://www.govariants.com/game/670952d842e74078c7a967fe) where players have often not realized they were holding up the round.
If this change is agreeable, I'm happy to follow up and update all the parallel variants.
Manually, I tried a fractional game, and observed:
a) players are still able to edit their moves for the duration of the round
b) only unstaged players are listed in the "Players to move" component
https://github.com/user-attachments/assets/c5eb156f-8eae-4c35-881d-76a4e18fa5c9
=> [fractional] only include unstaged players in nextToPlay

packages/shared/src/lib/__tests__/utils.test.ts, packages/shared/src/lib/utils.ts, packages/shared/src/variants/fractional/fractional.ts, packages/shared/src/variants/parallel.ts
- `Indexes` -> `Indices`, move `getNullIndices()` into utils
- Tbh I thought we had more than 2 parallel variants, hence the move to utils. 
- `parallel` to take the same `nextToMove` approach as `fractional` (see #381)
Tested:
- unit tests caught a lot!
- manually checked the parallel variant
=> Update parallel.ts to exclude unstaged players from nextToMove()

packages/vue-client/src/views/VariantDemoView.vue
Prevent an infinite loop that happens when variants mutate their config.
This is not a problem in GameView, because there we get the game state via server requests.
=> shallow copy config to allow variants to mutate it

packages/server/src/api.ts, packages/server/src/games.ts, packages/vue-client/src/views/GameView.vue
issue: #226 
- Add backend functionality to remove a minimum number of moves at the end of a game in order to restore a state that throws no errors. (does not restore time control, and so it may not work well for games with time control) This is accessable for all users, and I believe that's ok because it does not affect games that are not broken.
- If GameView is in an error state, display a button that triggers the game repair.
=> Repair game

packages/shared/src/variants/drift.ts
While looking through old games I noticed that some Drift Go games are broken. Examples:
https://www.govariants.com/game/65ccc298a932930e109c4ae1
https://www.govariants.com/game/65de4beedd5292c2a854e8e8
These games have an old config, and Drift Go does not have a sanitisation function yet.
=> [Drift] add sanitize function

packages/shared/src/index.ts, packages/shared/src/lib/__tests__/graph-utils.tests.ts, packages/shared/src/lib/graph-utils.ts, packages/shared/src/lib/graph.utils.ts, packages/shared/src/templates/pyramid_rules.ts, packages/shared/src/variants/pyramid.ts, packages/vue-client/src/components/GameCreation/PyramidConfigForm.vue, packages/vue-client/src/components/boards/MulticolorGraphBoard.vue, packages/vue-client/src/config_form_map.ts
- Add graph utils including a function to calculate generalised pyramid weights
- Refactor variant Pyramid s.t. it supports graph boards (grid board uses the classical weights schema)
- Weights are calculated once on client and stored in config
- Fix a bug of voronoi diagram
- I noticed that the voronoi calculations sometimes crash, e.g. with sunflower board. I'll try to fix that.
=> Generalised pyramid counting

packages/server/src/games.ts, packages/shared/src/api_types.ts
This is a proposal for solving the race condition bug in #226 
We introduce a new field for game documents `lastMoveTime`, and rewrite the db update call s.t. it fails if this field changed in the meantime.
This has the following advantages:
- No usage of transaction (this would add some starting hurdle for devs, because they would need to make sure their local db instance is a replica set. Also makes the code more verbose, and as @benjaminpjones wrote, fundamentally transactions solve a different problem - atomicity for a set of db updates)
- In the scenario of two (almost) simultaneous calls to `playMove`, exactly one request throws an error.
Also adds a schema for games, because it was somehow necessary for this update call (plus makes things easier).
add the following lines in …
=> Solve move race condition, add games schema
